# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fcb1e0b85f27a4a166946ee3a30070991d891f238c35680ee2e83edc46630f5ce10310c2dcbc5c0532e31d61b58a65dc733ba3f331860704033dd93f353ee55

test:
  secret_key_base: f92b342117529ebc71c389675749b6cddadb6878ff9b96f94d6eed9e2a435c62d2b1f447bcbafe685a1a4639286f4ece5526eb2bbcd775e97abf9dfab1aea702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
